#!/bin/bash

if [[ "$(which modprobe)" ]]; then
  load="modprobe"
  unload="modprobe -r"
else
  load="insmod"
  unload="rmmod"
fi

case "$1" in
  '')
    echo 'No module passed to the script.' >&2
    exit 2
    ;;
  *)
    mod_list="find /lib/modules/$(uname -r)/kernel -type f -printf '%f\n'"
    if [[ "$($mod_list | grep "$1" &> /dev/null)" ]]; then
      continue
    else
      echo "$1 isn't installed or isn't a valid module." >&2
      exit 1
    fi
    ;;
esac

if lsmod | grep "$1" &> /dev/null; then
  echo "$1 is loaded."
  read -n 1 -p "Do you want to remove it? [y/N]"
  echo
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    $unload $1
  else
    exit 1
  fi
else
  echo "$1 is not loaded."
  read -n 1 -p "Do you want to load it? [y/N]"
  echo
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    $unload $1
  else
    exit 1
  fi
fi
