#!/bin/bash

# Internal Field Separator
IFS=':'
for dir in $PATH; do
  echo $dir
done

while getopts ':f:c:hv' OPTION; do
  case "$OPTION" in
    f)
      classroom=$OPTARG
      ;;
    c)
      comm="${OPTARG^^}[@]"
      ;;
    h)
      echo "Usage: $(basename $0) [-v] [-h] [-f name] [-c 'command']" >&2
      exit 0
      ;;
    v)
      echo 'MA-MA MASIVO.' >&2
      echo 'Command line utility for massive working. Version 0.2' >&2
      exit 0
      ;;
    :)
      echo "Missing argument for $OPTARG" >&2
      echo "Usage: $(basename $0) [-v] [-h] [-f name] [-c 'command']" >&2
      exit 2
      ;;
    ?)
      echo "Invalid flag." >&2
      echo "Usage: $(basename $0) [-v] [-h] [-f name] [-c 'command']" >&2
      exit 2
      ;;
  esac
done
