#!/bin/bash

# Internal Field Separator
IFS=':'

list_files() {
  for file in $1/*; do
    if [[ -x $file ]]; then
      echo "  $file"
    fi
  done
}

while getopts ':f:' OPTION; do
  case "$OPTION" in
    d)
      dir="$OPTARG"
      ;;
    :)
      echo "Missing argument for $OPTARG" >&2
      exit 2
      ;;
    ?)
      echo "Invalid flag." >&2
      exit 2
      ;;
  esac
done

if [[ "$dir" ]]; then
  # =~ compares the two elements using regex.
  if [[ "${PATH[@]}" =~ "$dir" ]]; then
    echo "\$PATH contains $dir"

    list_files $dir

  else
    echo "\$PATH doesn't contain $dir"
  fi
else
  for directory in $PATH; do
    echo "$directory"

    list_files $directory

  done
fi
